// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUSXczC3P0NgP4ijfp26aT9V2zuvTfIIs',
    appId: '1:972801245266:web:68ac958e3913627a13df8b',
    messagingSenderId: '972801245266',
    projectId: 'sanpfind',
    authDomain: 'sanpfind.firebaseapp.com',
    storageBucket: 'sanpfind.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUjM7dW5WblWv0DNQx0-neojXn6XnnfbE',
    appId: '1:972801245266:android:6c44c4385c8d7c1f13df8b',
    messagingSenderId: '972801245266',
    projectId: 'sanpfind',
    storageBucket: 'sanpfind.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4fYzrq2a89-1hTwedqSWZbiEqjWwejYg',
    appId: '1:972801245266:ios:1d1f37762c3d22c713df8b',
    messagingSenderId: '972801245266',
    projectId: 'sanpfind',
    storageBucket: 'sanpfind.firebasestorage.app',
    iosBundleId: 'com.example.snapfind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4fYzrq2a89-1hTwedqSWZbiEqjWwejYg',
    appId: '1:972801245266:ios:1d1f37762c3d22c713df8b',
    messagingSenderId: '972801245266',
    projectId: 'sanpfind',
    storageBucket: 'sanpfind.firebasestorage.app',
    iosBundleId: 'com.example.snapfind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUSXczC3P0NgP4ijfp26aT9V2zuvTfIIs',
    appId: '1:972801245266:web:d45569ab4aa26ec213df8b',
    messagingSenderId: '972801245266',
    projectId: 'sanpfind',
    authDomain: 'sanpfind.firebaseapp.com',
    storageBucket: 'sanpfind.firebasestorage.app',
  );
}
